# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YVnLiP5ev5WXvVTQAd5skJLb8IH-XUvO
"""

pip install numpy

pip install smart_open[all]

pip install genism

!pip install gensim

pip install nltk



import nltk 
nltk.download('punkt')

text=" Welcome readers. I hope you find it interesting, Please do reply."

from nltk.tokenize import sent_tokenize

sent_tokenize(text)

tokenizers= nltk.data.load('tokenizers/punkt/english.pickle')

text=" Hello everyone. Hope all are fine and doing well. Hope you find the book interesting."

tokenizers.tokenize(text)

text="اهلا"

tokenizers.tokenize(text)

import nltk
french_tokenizer=nltk.data.load('tokenizers/punkt/french.pickle')

text=nltk.word_tokenize("Welcome readers. I hope you find it interesting. Please do reply..»")

print (text)



import nltk
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
tokenizer.tokenize("Have a nice day. You do great! don't ")

